# HoneyChest Configuration file for version 1.00
# @author syam <admin@sakura-server.net>
# BukkitDev: http://dev.bukkit.org/server-mods/honeychest/


#==================#
#   Basic Config   #
#==================#
# ItemID, used to create/remove honeychest
toolID: 269

kickFlag: true
banFlag: false

# Set to true for MCBans global bans. Be sure to follow their guidelines
globalBan: false

#====================#
#   Logging Config   #
#====================#
logToFile: true
logItems: true
logPath: plugins/Honeychest/honeychest.log

#=====================#
#   Messages Config   #
#=====================#
# There is a language file in English(default) and Japanese(ja_jp)
# If you want, you can create a custom message file in your language
messageLocale: default
# If it is true, hide some messages gives a hint for griefer
# For example, notBreakTrap, notPlaceChest and openedTrap messages on language file
hideTrapMessages: false
# If it is true, broadcast stolen items.
broadcastItems: true
# If it is true, hide "PlayerListener.youAreIgnore" message on language file
hideIgnoreMessage: true

#=====================#
#   Kick/Ban Config   #
#=====================#
# It is used to hookup with the MCBans.
# ** This option is Inactive! **
# I sent message to the MCBans about this option. waiting for a reply.
honeychestKickBanSender: '[Honeychest]'

honeychestKickReason: '[Honeychest] You have been caught steal items from honeychest.'
# If you set globalBAN: true, need to use the English here for their guidelines
# "!location!" string is replaced by "worldname:x,y,y"
honeychestBanReason: 'Steal items from HoneyChest. (!location!)'

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
version: 1.00