# HoneyChest author syam
# This is a default configuration file!


toolID: 269
kickFlag: true
banFlag: false

globalBan: false

logPath: plugins/Honeychest/honeychest.log

messageLocale: default
hiddenTrapMessages: false

honeychestKickBanSender: '[Honeychest]'
honeychestKickReason: '[Honeychest] You have been caught steal items from honeychest.'
honeychestBanReason: 'Steal items from HoneyChest. Goodbye!'